name: hospi_id_scanner
description: "Hospitality ID card scanner"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_ml_kit:
  http:
  google_mlkit_text_recognition:
  google_mlkit_document_scanner:
  connectivity_plus: ^6.0.3
  flutter_mrz_scanner:
  itc_sunmi_card_reader:
  mrz_parser:
  flutter_nfc_kit: ^3.0.0
  web_socket_channel:
  qr_flutter:
  camera: ^0.11.0+2
  mobile_scanner:
  ndef: ^0.3.4
  flutter_dotenv: ^5.1.0
  audioplayers: ^5.2.1
  path_provider: ^2.1.2
  nfc_manager: ^3.4.0
  image_picker: ^1.0.7
  permission_handler: ^11.0.0
  cupertino_icons: ^1.0.8
  flutter_tts: ^4.2.2
  shared_preferences: ^2.2.2

  crypto: ^3.0.3
  # ✅ NOUVELLES - À AJOUTER
  image: ^4.1.7  # Prétraitement d'image
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/prenoms.txt